// SPDX-License-Identifier: MIT
// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Run `npm run generate-errors` to update.

/**
 * Soroban contract error decoding utilities.
 * Maps raw contract error codes to human-readable messages.
 * Mirrors the PaymentError enum in contracts/ophirpay/src/lib.rs.
 */

export const CONTRACT_ERROR_MAP: Record<string, string> = {
  "1": "Contract not initialized: call init() first",
  "2": "Contract already initialized",
  "3": "Payment not found",
  "4": "Unauthorized: caller does not have permission",
  "5": "Invalid amount: must be greater than zero",
  "6": "Escrow not yet due: deadline has not passed",
  "7": "Escrow already released",
  "8": "Escrow not found",
  "9": "Stream not started: start time is in the future",
  "10": "Stream already cancelled",
  "11": "Stream not found",
  "12": "Stream fully claimed: no remaining balance",
  "13": "Batch too large: exceeds maximum recipients",
  "14": "Batch empty: no recipients provided",
  "15": "Token transfer failed",
  "16": "Insufficient balance to cover payment",
  "17": "Payment already cancelled",
  "18": "Contract paused: operations are temporarily disabled",
  "19": "No tokens available to withdraw",
  "20": "Upgrade not proposed: call propose_upgrade() first",
  "21": "Upgrade timelock active: 24-hour delay has not elapsed",
  "22": "Multisig not configured: call set_multisig_config() first",
  "23": "Not a signer: you are not in the multisig signer list",
  "24": "Already approved: duplicate approval detected",
  "25": "Threshold not met: insufficient approvals",
  "26": "Already executed: this action has already been processed",
  "27": "Not a role holder: insufficient RBAC permissions",
  "28": "Audit log empty: no entries recorded",
  "29": "Audit entry not found",
  "30": "Recurring payment not found",
  "31": "Recurring payment not yet due",
  "32": "Recurring payment already cancelled",
  "33": "Recurring payment expired: all payments completed",
  "34": "Fee configuration not found",
  "35": "Fee too high: exceeds maximum 1000 bps (10%)",
  "36": "Timelocked action not found",
  "37": "Timelocked action not yet due: 24-hour delay has not elapsed",
  "38": "Timelocked action already executed",
  "39": "Governance not configured: call configure_governance() first",
  "40": "Proposal not found",
  "41": "Voting period ended: proposal is closed",
  "42": "Proposal already executed",
  "43": "Quorum not met: insufficient votes cast",
  "44": "Proposal defeated: no votes exceeded yes votes",
  "45": "Deposit too low: must meet minimum proposal deposit",
  "46": "Spending limit expired: limit has been deactivated or expired",
  "47": "Refund not found",
  "48": "Refund already processed",
  "49": "Payment already refunded",
  "50": "Refund window expired",
  "51": "Already voted: each address may vote only once per proposal",
  "52": "Reentrant call detected: cross-contract reentry blocked",
  "53": "Spending cap exceeded: total spend exceeds authorization",
  "54": "Dispute already filed: a dispute exists for this transaction",
  "55": "Dispute not found",
  "56": "Dispute window expired: too late to file a dispute",
  "57": "Refund rejected: refund request was denied",
  "58": "Insufficient liquidity: pool cannot fulfill the order",
  "59": "Asset depegged: stablecoin is off its target peg",
  "60": "Proposal not passed: insufficient yes votes",
  "61": "Invalid signature: recovered signer does not match",
  "62": "Hook not found",
  "63": "Hook already exists: duplicate hook registration",
  "64": "Rate limit exceeded: too many requests",
  "65": "Asset not supported by this contract",
  "66": "Invalid metadata length: exceeds maximum allowed",
  "67": "Maximum recipients exceeded",
  "68": "Duplicate recipient in batch",
  "69": "Stream end time must be after start time",
  "70": "Escrow deadline must be in the future",
  "71": "Pending ownership transfer: accept or cancel first",
  "72": "Ownership transfer expired: timelock elapsed without acceptance",
  "73": "Invalid address format",
  "74": "Batch item failed: individual payment in batch error",
  "75": "Invalid recurring schedule type",
  "76": "Fee collector address not set",
  "77": "Emitter contract not linked: call set_emitter() first",
  "78": "Proposal deposit is locked: cannot withdraw while voting",
  "79": "Multisig signer limit exceeded",
  "80": "Invalid token contract address",
  "81": "Storage limit exceeded: contract storage is full",
  "82": "Contract migration required: upgrade to continue",
  "83": "Invalid event type for notification hook",
  "84": "Webhook URL too long: exceeds maximum length",
  "85": "Maximum notification hooks exceeded",
  "86": "Notification hook is not active",
  "87": "Cross-contract call failed",
  "88": "Invalid ScVal encoding in parameters",
  "89": "Unsupported operation: not available in this version",
  "90": "Contract not linked: configure linked contract first",
  "91": "Maximum signers exceeded for multisig",
  "92": "Zero address not allowed for this operation",
  "93": "Invalid network: wrong Stellar network configured",
  "94": "Staking not configured: call configure_staking() first",
  "95": "Staking already active: cannot modify while staking",
  "96": "Rewards pool empty: no rewards available for distribution",
  "97": "Unstaking period active: funds are still in cooldown",
  "98": "Minimum stake not met: stake must exceed the minimum",
  "99": "Maximum stake exceeded: stake cannot exceed the cap",
  "100": "Rewards already claimed for this epoch",
  "101": "Delegation not allowed: delegator is not authorized",
  "102": "Validator not active: selected validator is offline",
  "103": "Slashing condition met: stake is subject to penalty",
  "104": "Staking is currently paused",
  "105": "Compound rewards failed: auto-compound error",
  "106": "Yield too low: below minimum acceptable rate",
  "107": "Staking period not ended: cannot unstake yet",
  "108": "Reward distribution failed: transfer error",
  "109": "Delegator not authorized for this validator",
  "110": "Bridge not configured: call configure_bridge() first",
  "111": "Bridge is currently paused",
  "112": "Invalid source chain identifier",
  "113": "Invalid destination chain identifier",
  "114": "Cross-chain proof invalid: verification failed",
  "115": "Bridge relayer not set: configure relayer address",
  "116": "Bridge amount too low: below minimum transfer",
  "117": "Bridge amount too high: exceeds maximum transfer",
  "118": "Bridge transaction expired: timeout reached",
  "119": "Unsupported token pair for bridge transfer",
  "120": "Insurance fund not configured",
  "121": "Insurance fund empty: no funds available for claims",
  "122": "Insurance claim already filed for this event",
  "123": "Insurance claim rejected: does not meet criteria",
  "124": "Insurance claim window expired",
  "125": "Coverage limit exceeded: claim exceeds policy cap",
  "126": "Premium not paid: insurance coverage is inactive",
  "127": "Risk score too high: coverage denied",
  "128": "Underwriting failed: risk assessment error",
  "129": "Insurance operations are currently paused",
  "130": "KYC not completed: identity verification required",
  "131": "KYC tier too low: upgrade verification level",
  "132": "AML flag raised: transaction blocked for review",
  "133": "Sanctions list match: address is restricted",
  "134": "Identity verification failed: documents invalid",
  "135": "Travel rule violation: beneficiary info required",
  "136": "Jurisdiction not supported for this operation",
  "137": "Residency check failed: proof of residency required",
  "138": "Accreditation required: investor status not verified",
  "139": "Age verification failed: minimum age not met",
  "140": "Payment route not found: no valid path",
  "141": "Payment split failed: distribution error",
  "142": "Split percentage invalid: must sum to 100%",
  "143": "Route hop limit exceeded: path too long",
  "144": "Path payment too expensive: exceeds max fee",
  "145": "Liquidity pool not found for asset pair",
  "146": "Slippage exceeded: price moved beyond tolerance",
  "147": "Deadline exceeded: transaction too old",
  "148": "Price oracle stale: last update too old",
  "149": "Flash loan not repaid in same transaction",
  "150": "Out of gas: computation budget exhausted",
  "151": "Gas price too low: below network minimum",
  "152": "Gas refund failed: refund transfer error",
  "153": "Memory limit exceeded: allocation too large",
  "154": "Stack depth exceeded: too many nested calls",
  "155": "Instruction budget exceeded: too many operations",
  "156": "Read budget exceeded: too many storage reads",
  "157": "Write budget exceeded: too many storage writes",
  "158": "TTL too low: entry would expire too soon",
  "159": "Ledger entry limit reached: cannot create more",
  "160": "Oracle not configured: call set_oracle() first",
  "161": "Oracle timeout: response took too long",
  "162": "Oracle price deviation: outlier detected",
  "163": "Data feed unavailable: source is offline",
  "164": "Data feed tampered: integrity check failed",
  "165": "Oracle already active: duplicate registration",
  "166": "Price feed stale: last update exceeds threshold",
  "167": "Confidence interval too wide: price uncertain",
  "168": "Oracle signature invalid: attestation failed",
  "169": "Maximum price age exceeded: feed too old",
  "170": "Batch execution timeout: not all items finished",
  "171": "Batch partial failure: some items failed",
  "172": "Stream rate invalid: must be positive non-zero",
  "173": "Stream duration too long: exceeds maximum",
  "174": "Stream claim too early: minimum interval not met",
  "175": "Batch authorization failed: signer rejected",
  "176": "Batch duplicate ID: transaction already processed",
  "177": "Stream beneficiary unchanged: same as current",
  "178": "Stream transfer not allowed: stream is non-transferable",
  "179": "Batch cleanup failed: stale state removal error",
  "180": "Dispute not open: no active dispute found",
  "181": "Dispute arbiter not set: configure arbiter first",
  "182": "Dispute evidence required: must submit proof",
  "183": "Dispute already resolved: final decision made",
  "184": "Dispute resolution timed out: arbiter did not respond",
  "185": "Arbiter not authorized: not in approved list",
  "186": "Mediation failed: parties could not agree",
  "187": "Appeal window closed: too late to appeal",
  "188": "Dispute bond insufficient: must stake more",
  "189": "Dispute escalation failed: higher authority error",
  "190": "Maximum storage entries reached: ledger full",
  "191": "Storage fee not paid: rent payment required",
  "192": "Archive entry not found: record already pruned",
  "193": "State sync mismatch: ledger state inconsistent",
  "194": "Migration in progress: try again later",
  "195": "Rollback detected: chain reorganization",
  "196": "Snapshot verification failed: hash mismatch",
  "197": "Contract deprecated: use the new version",
  "198": "Emergency shutdown active: all operations blocked",
  "199": "System overloaded: too many concurrent requests",
  "200": "Delegate not active: delegator is offline or disabled",
  "201": "Delegation expired: delegation period has ended",
  "202": "Vote delegation mismatch: delegate does not match voter",
  "203": "Proposal cancelled: proposal was withdrawn by creator",
  "204": "Proposal quorum changed: quorum was modified mid-vote",
  "205": "Emergency governance paused: voting is temporarily suspended",
  "206": "Governance token locked: tokens are in a lockup period",
  "207": "Voting power frozen: votes are immobilized by a freeze",
  "208": "Proposal execution failed: on-chain execution reverted",
  "209": "Governance upgrade pending: upgrade has not been finalized",
  "210": "Treasury not configured: call configure_treasury() first",
  "211": "Treasury withdrawal pending: timelock has not elapsed",
  "212": "Reserve requirement not met: minimum reserve ratio breached",
  "213": "Treasury multisig required: threshold signatures missing",
  "214": "Reserve asset unavailable: asset cannot be used as reserve",
  "215": "Treasury report mismatch: balance does not match ledger",
  "216": "Reserve ratio breached: reserves fell below the minimum",
  "217": "Treasury audit failed: reconciliation check did not pass",
  "218": "Reserve rebalance failed: allocation update reverted",
  "219": "Treasury access revoked: caller permissions were removed",
  "220": "Token already listed: asset is already supported",
  "221": "Token delisting pending: removal is awaiting timelock",
  "222": "Asset pair not found: no market exists for the pair",
  "223": "Token supply cap exceeded: mint would exceed the cap",
  "224": "Minting paused: new issuance is temporarily disabled",
  "225": "Burning paused: token destruction is temporarily disabled",
  "226": "Token frozen: asset transfers are blocked",
  "227": "Asset trustline missing: trustline must be established",
  "228": "Token metadata invalid: name, symbol, or decimals malformed",
  "229": "Asset migration pending: upgrade to new contract incomplete",
  "230": "Lending pool not configured: call configure_lending() first",
  "231": "Loan not found",
  "232": "Loan already repaid: no outstanding balance",
  "233": "Collateral insufficient: below required ratio",
  "234": "Liquidation pending: position is in the process of liquidation",
  "235": "Interest rate invalid: outside allowed bounds",
  "236": "Credit limit exceeded: borrow would exceed the limit",
  "237": "Loan maturity reached: repayment is now due",
  "238": "Collateral frozen: collateral cannot be moved",
  "239": "Lending paused: borrow and lend operations are suspended",
  "240": "Subscription not found",
  "241": "Subscription already cancelled",
  "242": "Subscription renewal failed: payment did not settle",
  "243": "Billing cycle invalid: interval is not supported",
  "244": "Subscription paused: renewals are temporarily halted",
  "245": "Trial period expired: paid plan is now required",
  "246": "Payment method invalid: token or method not accepted",
  "247": "Subscription tier not allowed: upgrade is restricted",
  "248": "Usage quota exceeded: plan allowance has been reached",
  "249": "Subscription upgrade pending: change has not been applied",
  "250": "Zero-knowledge proof invalid: verification failed",
  "251": "Privacy pool not configured: call configure_privacy() first",
  "252": "Commitment already spent: double-spend detected",
  "253": "Nullifier already used: proof was previously consumed",
  "254": "Merkle path invalid: membership proof is malformed",
  "255": "Privacy deposit too low: below the minimum amount",
  "256": "Privacy withdrawal pending: timelock has not elapsed",
  "257": "Stealth address invalid: cannot derive recipient",
  "258": "Confidential transfer failed: shielded amount mismatch",
  "259": "Privacy paused: shielded operations are suspended",
  "260": "Notification service down: delivery backend unavailable",
  "261": "Message too long: exceeds maximum length",
  "262": "Recipient unsubscribed: target has opted out",
  "263": "Notification delivery failed: could not reach recipient",
  "264": "Notification rate limited: too many messages sent",
  "265": "Message signature invalid: sender could not be verified",
  "266": "Inbox full: recipient storage limit reached",
  "267": "Notification template invalid: malformed payload",
  "268": "Message expired: delivery window has passed",
  "269": "Notification channel closed: channel is no longer active",
  "270": "Report generation failed: aggregation error",
  "271": "Analytics data missing: required metrics unavailable",
  "272": "Metric out of range: value exceeds allowed bounds",
  "273": "Report too large: exceeds maximum output size",
  "274": "Snapshot not found: requested point-in-time state missing",
  "275": "Aggregation window invalid: time range is malformed",
  "276": "Data retention expired: historical data was pruned",
  "277": "Report access denied: insufficient permissions",
  "278": "Analytics quota exceeded: too many report requests",
  "279": "Export format unsupported: requested format is not available",
  "280": "SEP protocol violation: interface contract was not honored",
  "281": "Asset not SEP-compliant: missing required SEP behavior",
  "282": "Cross-contract version mismatch: incompatible API versions",
  "283": "Interface not implemented: required method is missing",
  "284": "Standards compliance failed: validation did not pass",
  "285": "Protocol upgrade required: dependency is out of date",
  "286": "Interop handshake failed: connection could not be established",
  "287": "Namespace collision: identifier is already registered",
  "288": "External system unavailable: dependency is offline",
  "289": "Interop rate limit exceeded: too many cross-system calls",
  "290": "Contract upgrade scheduled: upgrade is pending execution",
  "291": "Maintenance mode active: operations temporarily disabled",
  "292": "Circuit breaker tripped: safety threshold was exceeded",
  "293": "Emergency freeze active: all state changes are blocked",
  "294": "System clock drift detected: ledger time is inconsistent",
  "295": "Ledger version unsupported: network upgrade required",
  "296": "Network partition detected: consensus is unavailable",
  "297": "Resource exhaustion warning: limits are near capacity",
  "298": "Grace period active: transitional restrictions in effect",
  "299": "Configuration invalid: stored configuration is malformed",
  "300": "System fatal error: unrecoverable internal failure",
  "301": "Revocation not found",
  "302": "Revocation not due",
  "303": "Revocation already executed",
  "304": "Cannot revoke self",
  "305": "No pending ownership transfer",
  "306": "Math overflow",
  "307": "Stream accounting invariant violated: refused to pay an inconsistent amount",
};

/**
 * Attempt to decode a Soroban contract error from a diagnostic event
 * or raw error value. Falls back to the raw value if unknown.
 */
export function decodeContractError(rawError: string): string {
  const trimmed = rawError.trim();

  // Check for Error(Contract, #N) pattern
  const codeMatch = trimmed.match(/Error\(Contract,\s*#(\d+)\)/);
  if (codeMatch && CONTRACT_ERROR_MAP[codeMatch[1]]) {
    return CONTRACT_ERROR_MAP[codeMatch[1]];
  }

  // Check for numeric error codes from diagnostic events
  if (CONTRACT_ERROR_MAP[trimmed]) {
    return CONTRACT_ERROR_MAP[trimmed];
  }

  // Return raw error if we can't decode it
  return rawError;
}

/**
 * Get all known contract errors for documentation / tooltips.
 */
export function getContractErrorCatalog(): { code: string; message: string }[] {
  return Object.entries(CONTRACT_ERROR_MAP)
    .map(([code, message]) => ({ code, message }))
    .sort((a, b) => parseInt(a.code) - parseInt(b.code));
}
