import { globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// eslint-config-next >= 16 ships native flat config arrays via its
// `core-web-vitals` and `typescript` subpath exports — no FlatCompat needed.
const eslintConfig = [
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // react-hooks v6 (bundled with eslint-config-next 16) enables these
      // opinionated React-Compiler-era rules by default. They flag
      // long-established idiomatic patterns used throughout this codebase
      // (data-fetch-in-effect, matchMedia/event listeners, stable refs,
      // usePrevious, optimistic Date.now() updates for IDs/countdowns).
      // Suppress them until the codebase is migrated toward React Compiler
      // semantics.
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/refs": "off",
      "react-hooks/purity": "off",
    },
  },
  globalIgnores([
    ".next/**",
    "node_modules/**",
    "contracts/**",
    "public/**",
    "prisma/**",
    "scripts/**",
    "examples/**",
    "*.config.{mjs,ts}",
    "next-env.d.ts", // auto-generated by Next.js, not committed
    "playwright-report/**",
    "test-results/**",
    "coverage/**",
  ]),
];

export default eslintConfig;
