import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest.setup.ts"],
    include: [
      "src/__tests__/**/*.test.{ts,tsx}",
      "scripts/**/*.test.{ts,tsx}",
      "tests/**/*.test.{ts,tsx}",
    ],
    env: {
      NEXT_PUBLIC_CONTRACT_ID: "CCQGGUJRRVXMHNEX2RYPODGJE2YRMYY4Y7A3KTJH3QP2LWZLTCOPRPET",
      NEXT_PUBLIC_EMITTER_CONTRACT_ID: "CDAVU2XJ7C2Y52GRJZKRG3HDI7AJ2K2FHAFH5FPDTSUQAV7XNBQNNVAN",
      NEXT_PUBLIC_CHAIN_READ_SOURCE: "GACNKEDGJYLLVQDXWYEEPB47Y3JEV5JNZ3RQANTJIVKKEOXX4NC4YWHU",
    },
    coverage: {
      provider: "v8",
      include: [
        "src/lib/**",
        "src/components/**",
        "src/hooks/**",
        "src/app/**",
      ],
      exclude: [
        "src/__tests__/**",
        "**/*.test.{ts,tsx}",
        "src/types/**",
        "**/*.d.ts",
        "src/lib/wallets/**",
        "src/lib/index.ts",
        "src/lib/contracts.ts",
        "src/lib/contract-advanced.ts",
        "src/lib/contract-events.ts",
        "src/lib/stellar.ts",
        "src/lib/rpc-failover.ts",
        "src/lib/events/event-source.ts",
        "src/lib/api-client.ts",
        "src/lib/demo-mode.ts",
        "src/instrumentation.ts",
        "src/lib/startup.ts",
        "src/lib/sentry.ts",
        "src/lib/deploy-verify.ts",
        "src/hooks/useMultiWallet.tsx",
        "src/hooks/useFreighter.tsx",
        "src/hooks/useTheme.tsx",
        "src/hooks/useRetry.ts",
        "src/hooks/useApiQuery.ts",
        "src/hooks/useNetworkChange.ts",
        "src/hooks/useErrorTracker.ts",
        "src/hooks/useKeyboardShortcuts.ts",
        "src/hooks/useLocalStorage.ts",
        "src/lib/ab-test.ts",
        "src/lib/address-book.ts",
        "src/lib/api-cache.ts",
        "src/lib/audit.ts",
        "src/lib/batch-validator.ts",
        "src/lib/chart-data.ts",
        "src/lib/client-auth.ts",
        "src/lib/client-version.ts",
        "src/lib/csv-import.ts",
        "src/lib/payment-link.ts",
        "src/lib/prisma-logger.ts",
        "src/lib/query-params.ts",
        "src/lib/soft-delete.ts",
        "src/components/ui/index.ts",
        "src/hooks/index.ts",
        "src/lib/time.ts",
        "src/lib/trustline.ts",
        "src/lib/version-script.ts",
        "src/lib/web-vitals.ts",
      ],
      thresholds: {
        statements: 69,
        branches: 66,
        functions: 66,
        lines: 71,
        "src/app/api/**": {
          statements: 71,
          branches: 68,
          functions: 70,
          lines: 74,
        },
        "src/lib/{auth-rate-limit,auth-session,challenge,csrf,csrf-route-registry,crypto,lookup-rate-limit,sanitize,session,validation-schemas,webhook-url-guard}.ts":
          {
            statements: 90,
            branches: 89,
            functions: 93,
            lines: 92,
          },
        "src/lib/**": {
          statements: 87,
          branches: 84,
          functions: 90,
          lines: 89,
        },
        "src/components/**": {
          statements: 70,
          branches: 74,
          functions: 69,
          lines: 71,
        },
        "src/hooks/**": {
          statements: 95,
          branches: 82,
          functions: 95,
          lines: 97,
        },
        "src/app/**": {
          statements: 55,
          branches: 52,
          functions: 43,
          lines: 56,
        },
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});