#![cfg(test)]
// SPDX-License-Identifier: MIT
//
// Issue #717 — Assert every PaymentError variant has a unique numeric code.
//
// A duplicate discriminant compiles fine but produces wrong user-facing
// messages at runtime because the TypeScript catalog (src/lib/contract-errors.ts)
// maps codes 1:1. This test enumerates all discriminants and fails with the
// offending variant names if a collision is found.

use ophirpay_contract::PaymentError;
use std::collections::HashMap;

/// Returns a list of (variant_name, discriminant) for every PaymentError variant.
/// Maintained by hand because Soroban's `#[contracterror]` does not expose an
/// iterator — but a missing entry is caught by the exhaustive match below.
fn all_variants() -> Vec<(&'static str, u32)> {
    vec![
        ("NotInitialized", PaymentError::NotInitialized as u32),
        ("AlreadyInitialized", PaymentError::AlreadyInitialized as u32),
        ("PaymentNotFound", PaymentError::PaymentNotFound as u32),
        ("Unauthorized", PaymentError::Unauthorized as u32),
        ("InvalidAmount", PaymentError::InvalidAmount as u32),
        ("EscrowNotDue", PaymentError::EscrowNotDue as u32),
        ("EscrowAlreadyReleased", PaymentError::EscrowAlreadyReleased as u32),
        ("EscrowNotFound", PaymentError::EscrowNotFound as u32),
        ("StreamNotStarted", PaymentError::StreamNotStarted as u32),
        ("StreamAlreadyCancelled", PaymentError::StreamAlreadyCancelled as u32),
        ("StreamNotFound", PaymentError::StreamNotFound as u32),
        ("StreamFullyClaimed", PaymentError::StreamFullyClaimed as u32),
        ("BatchTooLarge", PaymentError::BatchTooLarge as u32),
        ("BatchEmpty", PaymentError::BatchEmpty as u32),
        ("TokenTransferFailed", PaymentError::TokenTransferFailed as u32),
        ("InsufficientBalance", PaymentError::InsufficientBalance as u32),
        ("PaymentAlreadyCancelled", PaymentError::PaymentAlreadyCancelled as u32),
        ("ContractPaused", PaymentError::ContractPaused as u32),
        ("NoTokensToWithdraw", PaymentError::NoTokensToWithdraw as u32),
        ("UpgradeNotProposed", PaymentError::UpgradeNotProposed as u32),
        ("UpgradeTimelockActive", PaymentError::UpgradeTimelockActive as u32),
        ("MultisigNotConfigured", PaymentError::MultisigNotConfigured as u32),
        ("NotASigner", PaymentError::NotASigner as u32),
        ("AlreadyApproved", PaymentError::AlreadyApproved as u32),
        ("ThresholdNotMet", PaymentError::ThresholdNotMet as u32),
        ("AlreadyExecuted", PaymentError::AlreadyExecuted as u32),
        ("NotARoleHolder", PaymentError::NotARoleHolder as u32),
        ("AuditLogEmpty", PaymentError::AuditLogEmpty as u32),
        ("AuditEntryNotFound", PaymentError::AuditEntryNotFound as u32),
        ("RecurringNotFound", PaymentError::RecurringNotFound as u32),
        ("RecurringNotDue", PaymentError::RecurringNotDue as u32),
        ("RecurringAlreadyCancelled", PaymentError::RecurringAlreadyCancelled as u32),
        ("RecurringExpired", PaymentError::RecurringExpired as u32),
        ("FeeConfigNotFound", PaymentError::FeeConfigNotFound as u32),
        ("FeeTooHigh", PaymentError::FeeTooHigh as u32),
        ("TimelockNotFound", PaymentError::TimelockNotFound as u32),
        ("TimelockNotDue", PaymentError::TimelockNotDue as u32),
        ("TimelockAlreadyExecuted", PaymentError::TimelockAlreadyExecuted as u32),
        ("GovernanceNotConfigured", PaymentError::GovernanceNotConfigured as u32),
        ("ProposalNotFound", PaymentError::ProposalNotFound as u32),
        ("VotingPeriodEnded", PaymentError::VotingPeriodEnded as u32),
        ("ProposalAlreadyExecuted", PaymentError::ProposalAlreadyExecuted as u32),
        ("QuorumNotMet", PaymentError::QuorumNotMet as u32),
        ("ProposalDefeated", PaymentError::ProposalDefeated as u32),
        ("DepositTooLow", PaymentError::DepositTooLow as u32),
        ("SpendingLimitExpired", PaymentError::SpendingLimitExpired as u32),
        ("RefundNotFound", PaymentError::RefundNotFound as u32),
        ("RefundAlreadyProcessed", PaymentError::RefundAlreadyProcessed as u32),
        ("PaymentAlreadyRefunded", PaymentError::PaymentAlreadyRefunded as u32),
        ("RefundWindowExpired", PaymentError::RefundWindowExpired as u32),
        ("AlreadyVoted", PaymentError::AlreadyVoted as u32),
        ("ReentrantCall", PaymentError::ReentrantCall as u32),
        ("SpendCapExceeded", PaymentError::SpendCapExceeded as u32),
        ("DisputeAlreadyFiled", PaymentError::DisputeAlreadyFiled as u32),
        ("DisputeNotFound", PaymentError::DisputeNotFound as u32),
        ("DisputeWindowExpired", PaymentError::DisputeWindowExpired as u32),
        ("RefundRejected", PaymentError::RefundRejected as u32),
        ("InsufficientLiquidity", PaymentError::InsufficientLiquidity as u32),
        ("AssetDepegged", PaymentError::AssetDepegged as u32),
        ("ProposalNotPassed", PaymentError::ProposalNotPassed as u32),
        ("InvalidSignature", PaymentError::InvalidSignature as u32),
        ("HookNotFound", PaymentError::HookNotFound as u32),
        ("HookAlreadyExists", PaymentError::HookAlreadyExists as u32),
        ("RateLimitExceeded", PaymentError::RateLimitExceeded as u32),
        ("AssetNotSupported", PaymentError::AssetNotSupported as u32),
        ("InvalidMetadataLength", PaymentError::InvalidMetadataLength as u32),
        ("MaxRecipientsExceeded", PaymentError::MaxRecipientsExceeded as u32),
        ("DuplicateRecipient", PaymentError::DuplicateRecipient as u32),
        ("StreamEndBeforeStart", PaymentError::StreamEndBeforeStart as u32),
        ("EscrowDeadlineInPast", PaymentError::EscrowDeadlineInPast as u32),
        ("PendingOwnershipTransfer", PaymentError::PendingOwnershipTransfer as u32),
        ("OwnershipTransferExpired", PaymentError::OwnershipTransferExpired as u32),
        ("InvalidAddressFormat", PaymentError::InvalidAddressFormat as u32),
        ("BatchItemFailed", PaymentError::BatchItemFailed as u32),
        ("RecurringScheduleInvalid", PaymentError::RecurringScheduleInvalid as u32),
        ("FeeCollectorNotSet", PaymentError::FeeCollectorNotSet as u32),
        ("EmitterNotLinked", PaymentError::EmitterNotLinked as u32),
        ("ProposalDepositLocked", PaymentError::ProposalDepositLocked as u32),
        ("MultisigSignerLimit", PaymentError::MultisigSignerLimit as u32),
        ("InvalidTokenContract", PaymentError::InvalidTokenContract as u32),
        ("StorageLimitExceeded", PaymentError::StorageLimitExceeded as u32),
        ("ContractMigrationRequired", PaymentError::ContractMigrationRequired as u32),
        ("InvalidEventType", PaymentError::InvalidEventType as u32),
        ("WebhookUrlTooLong", PaymentError::WebhookUrlTooLong as u32),
        ("MaxHooksExceeded", PaymentError::MaxHooksExceeded as u32),
        ("HookNotActive", PaymentError::HookNotActive as u32),
        ("CrossContractCallFailed", PaymentError::CrossContractCallFailed as u32),
        ("InvalidScValEncoding", PaymentError::InvalidScValEncoding as u32),
        ("UnsupportedOperation", PaymentError::UnsupportedOperation as u32),
        ("ContractNotLinked", PaymentError::ContractNotLinked as u32),
        ("MaxSignersExceeded", PaymentError::MaxSignersExceeded as u32),
        ("ZeroAddressNotAllowed", PaymentError::ZeroAddressNotAllowed as u32),
        ("InvalidNetwork", PaymentError::InvalidNetwork as u32),
        ("StakingNotConfigured", PaymentError::StakingNotConfigured as u32),
        ("StakingAlreadyActive", PaymentError::StakingAlreadyActive as u32),
        ("RewardsPoolEmpty", PaymentError::RewardsPoolEmpty as u32),
        ("UnstakingPeriodActive", PaymentError::UnstakingPeriodActive as u32),
        ("MinimumStakeNotMet", PaymentError::MinimumStakeNotMet as u32),
        ("MaximumStakeExceeded", PaymentError::MaximumStakeExceeded as u32),
        ("RewardsAlreadyClaimed", PaymentError::RewardsAlreadyClaimed as u32),
        ("DelegationNotAllowed", PaymentError::DelegationNotAllowed as u32),
        ("ValidatorNotActive", PaymentError::ValidatorNotActive as u32),
        ("SlashingConditionMet", PaymentError::SlashingConditionMet as u32),
        ("StakingPaused", PaymentError::StakingPaused as u32),
        ("CompoundRewardsFailed", PaymentError::CompoundRewardsFailed as u32),
        ("YieldTooLow", PaymentError::YieldTooLow as u32),
        ("StakingPeriodNotEnded", PaymentError::StakingPeriodNotEnded as u32),
        ("RewardDistributionFailed", PaymentError::RewardDistributionFailed as u32),
        ("UnauthorizedDelegator", PaymentError::UnauthorizedDelegator as u32),
        ("BridgeNotConfigured", PaymentError::BridgeNotConfigured as u32),
        ("BridgePaused", PaymentError::BridgePaused as u32),
        ("InvalidSourceChain", PaymentError::InvalidSourceChain as u32),
        ("InvalidDestinationChain", PaymentError::InvalidDestinationChain as u32),
        ("CrossChainProofInvalid", PaymentError::CrossChainProofInvalid as u32),
        ("BridgeRelayerNotSet", PaymentError::BridgeRelayerNotSet as u32),
        ("BridgeAmountTooLow", PaymentError::BridgeAmountTooLow as u32),
        ("BridgeAmountTooHigh", PaymentError::BridgeAmountTooHigh as u32),
        ("BridgeTransactionExpired", PaymentError::BridgeTransactionExpired as u32),
        ("UnsupportedTokenPair", PaymentError::UnsupportedTokenPair as u32),
        ("InsuranceFundNotConfigured", PaymentError::InsuranceFundNotConfigured as u32),
        ("InsuranceFundEmpty", PaymentError::InsuranceFundEmpty as u32),
        ("InsuranceClaimAlreadyFiled", PaymentError::InsuranceClaimAlreadyFiled as u32),
        ("InsuranceClaimRejected", PaymentError::InsuranceClaimRejected as u32),
        ("InsuranceClaimWindowExpired", PaymentError::InsuranceClaimWindowExpired as u32),
        ("CoverageLimitExceeded", PaymentError::CoverageLimitExceeded as u32),
        ("PremiumNotPaid", PaymentError::PremiumNotPaid as u32),
        ("RiskScoreTooHigh", PaymentError::RiskScoreTooHigh as u32),
        ("UnderwritingFailed", PaymentError::UnderwritingFailed as u32),
        ("InsurancePaused", PaymentError::InsurancePaused as u32),
        ("KYCNotCompleted", PaymentError::KYCNotCompleted as u32),
        ("KYCTierTooLow", PaymentError::KYCTierTooLow as u32),
        ("AMLFlagRaised", PaymentError::AMLFlagRaised as u32),
        ("SanctionsListMatch", PaymentError::SanctionsListMatch as u32),
        ("IdentityVerificationFailed", PaymentError::IdentityVerificationFailed as u32),
        ("TravelRuleViolation", PaymentError::TravelRuleViolation as u32),
        ("JurisdictionNotSupported", PaymentError::JurisdictionNotSupported as u32),
        ("ResidencyCheckFailed", PaymentError::ResidencyCheckFailed as u32),
        ("AccreditationRequired", PaymentError::AccreditationRequired as u32),
        ("AgeVerificationFailed", PaymentError::AgeVerificationFailed as u32),
        ("PaymentRouteNotFound", PaymentError::PaymentRouteNotFound as u32),
        ("PaymentSplitFailed", PaymentError::PaymentSplitFailed as u32),
        ("SplitPercentageInvalid", PaymentError::SplitPercentageInvalid as u32),
        ("RouteHopLimitExceeded", PaymentError::RouteHopLimitExceeded as u32),
        ("PathPaymentTooExpensive", PaymentError::PathPaymentTooExpensive as u32),
        ("LiquidityPoolNotFound", PaymentError::LiquidityPoolNotFound as u32),
        ("SlippageExceeded", PaymentError::SlippageExceeded as u32),
        ("DeadlineExceeded", PaymentError::DeadlineExceeded as u32),
        ("PriceOracleStale", PaymentError::PriceOracleStale as u32),
        ("FlashLoanNotRepaid", PaymentError::FlashLoanNotRepaid as u32),
        ("OutOfGas", PaymentError::OutOfGas as u32),
        ("GasPriceTooLow", PaymentError::GasPriceTooLow as u32),
        ("GasRefundFailed", PaymentError::GasRefundFailed as u32),
        ("MemoryLimitExceeded", PaymentError::MemoryLimitExceeded as u32),
        ("StackDepthExceeded", PaymentError::StackDepthExceeded as u32),
        ("InstructionBudgetExceeded", PaymentError::InstructionBudgetExceeded as u32),
        ("ReadBudgetExceeded", PaymentError::ReadBudgetExceeded as u32),
        ("WriteBudgetExceeded", PaymentError::WriteBudgetExceeded as u32),
        ("TTLTooLow", PaymentError::TTLTooLow as u32),
        ("LedgerEntryLimitReached", PaymentError::LedgerEntryLimitReached as u32),
        ("OracleNotConfigured", PaymentError::OracleNotConfigured as u32),
        ("OracleTimeout", PaymentError::OracleTimeout as u32),
        ("OraclePriceDeviation", PaymentError::OraclePriceDeviation as u32),
        ("DataFeedUnavailable", PaymentError::DataFeedUnavailable as u32),
        ("DataFeedTampered", PaymentError::DataFeedTampered as u32),
        ("OracleAlreadyActive", PaymentError::OracleAlreadyActive as u32),
        ("PriceFeedStale", PaymentError::PriceFeedStale as u32),
        ("ConfidenceIntervalTooWide", PaymentError::ConfidenceIntervalTooWide as u32),
        ("OracleSignatureInvalid", PaymentError::OracleSignatureInvalid as u32),
        ("MaxPriceAgeExceeded", PaymentError::MaxPriceAgeExceeded as u32),
        ("BatchExecutionTimeout", PaymentError::BatchExecutionTimeout as u32),
        ("BatchPartialFailure", PaymentError::BatchPartialFailure as u32),
        ("StreamRateInvalid", PaymentError::StreamRateInvalid as u32),
        ("StreamTooLong", PaymentError::StreamTooLong as u32),
        ("StreamClaimTooEarly", PaymentError::StreamClaimTooEarly as u32),
        ("BatchAuthorizationFailed", PaymentError::BatchAuthorizationFailed as u32),
        ("BatchDuplicateId", PaymentError::BatchDuplicateId as u32),
        ("StreamBeneficiaryUnchanged", PaymentError::StreamBeneficiaryUnchanged as u32),
        ("StreamTransferNotAllowed", PaymentError::StreamTransferNotAllowed as u32),
        ("BatchCleanupFailed", PaymentError::BatchCleanupFailed as u32),
        ("DisputeNotOpen", PaymentError::DisputeNotOpen as u32),
        ("DisputeArbiterNotSet", PaymentError::DisputeArbiterNotSet as u32),
        ("DisputeEvidenceRequired", PaymentError::DisputeEvidenceRequired as u32),
        ("DisputeAlreadyResolved", PaymentError::DisputeAlreadyResolved as u32),
        ("DisputeResolutionTimedOut", PaymentError::DisputeResolutionTimedOut as u32),
        ("ArbiterNotAuthorized", PaymentError::ArbiterNotAuthorized as u32),
        ("MediationFailed", PaymentError::MediationFailed as u32),
        ("AppealWindowClosed", PaymentError::AppealWindowClosed as u32),
        ("DisputeBondInsufficient", PaymentError::DisputeBondInsufficient as u32),
        ("DisputeEscalationFailed", PaymentError::DisputeEscalationFailed as u32),
        ("MaxStorageEntriesReached", PaymentError::MaxStorageEntriesReached as u32),
        ("StorageFeeNotPaid", PaymentError::StorageFeeNotPaid as u32),
        ("ArchiveEntryNotFound", PaymentError::ArchiveEntryNotFound as u32),
        ("StateSyncMismatch", PaymentError::StateSyncMismatch as u32),
        ("MigrationInProgress", PaymentError::MigrationInProgress as u32),
        ("RollbackDetected", PaymentError::RollbackDetected as u32),
        ("SnapshotVerificationFailed", PaymentError::SnapshotVerificationFailed as u32),
        ("ContractDeprecated", PaymentError::ContractDeprecated as u32),
        ("EmergencyShutdownActive", PaymentError::EmergencyShutdownActive as u32),
        ("SystemOverloaded", PaymentError::SystemOverloaded as u32),
        ("DelegateNotActive", PaymentError::DelegateNotActive as u32),
        ("DelegationExpired", PaymentError::DelegationExpired as u32),
        ("VoteDelegationMismatch", PaymentError::VoteDelegationMismatch as u32),
        ("ProposalCancelled", PaymentError::ProposalCancelled as u32),
        ("ProposalQuorumChanged", PaymentError::ProposalQuorumChanged as u32),
        ("EmergencyGovernancePaused", PaymentError::EmergencyGovernancePaused as u32),
        ("GovernanceTokenLocked", PaymentError::GovernanceTokenLocked as u32),
        ("VotingPowerFrozen", PaymentError::VotingPowerFrozen as u32),
        ("ProposalExecutionFailed", PaymentError::ProposalExecutionFailed as u32),
        ("GovernanceUpgradePending", PaymentError::GovernanceUpgradePending as u32),
        ("TreasuryNotConfigured", PaymentError::TreasuryNotConfigured as u32),
        ("TreasuryWithdrawalPending", PaymentError::TreasuryWithdrawalPending as u32),
        ("ReserveRequirementNotMet", PaymentError::ReserveRequirementNotMet as u32),
        ("TreasuryMultisigRequired", PaymentError::TreasuryMultisigRequired as u32),
        ("ReserveAssetUnavailable", PaymentError::ReserveAssetUnavailable as u32),
        ("TreasuryReportMismatch", PaymentError::TreasuryReportMismatch as u32),
        ("ReserveRatioBreached", PaymentError::ReserveRatioBreached as u32),
        ("TreasuryAuditFailed", PaymentError::TreasuryAuditFailed as u32),
        ("ReserveRebalanceFailed", PaymentError::ReserveRebalanceFailed as u32),
        ("TreasuryAccessRevoked", PaymentError::TreasuryAccessRevoked as u32),
        ("TokenAlreadyListed", PaymentError::TokenAlreadyListed as u32),
        ("TokenDelistingPending", PaymentError::TokenDelistingPending as u32),
        ("AssetPairNotFound", PaymentError::AssetPairNotFound as u32),
        ("TokenSupplyCapExceeded", PaymentError::TokenSupplyCapExceeded as u32),
        ("MintingPaused", PaymentError::MintingPaused as u32),
        ("BurningPaused", PaymentError::BurningPaused as u32),
        ("TokenFrozen", PaymentError::TokenFrozen as u32),
        ("AssetTrustlineMissing", PaymentError::AssetTrustlineMissing as u32),
        ("TokenMetadataInvalid", PaymentError::TokenMetadataInvalid as u32),
        ("AssetMigrationPending", PaymentError::AssetMigrationPending as u32),
        ("LendingPoolNotConfigured", PaymentError::LendingPoolNotConfigured as u32),
        ("LoanNotFound", PaymentError::LoanNotFound as u32),
        ("LoanAlreadyRepaid", PaymentError::LoanAlreadyRepaid as u32),
        ("CollateralInsufficient", PaymentError::CollateralInsufficient as u32),
        ("LiquidationPending", PaymentError::LiquidationPending as u32),
        ("InterestRateInvalid", PaymentError::InterestRateInvalid as u32),
        ("CreditLimitExceeded", PaymentError::CreditLimitExceeded as u32),
        ("LoanMaturityReached", PaymentError::LoanMaturityReached as u32),
        ("CollateralFrozen", PaymentError::CollateralFrozen as u32),
        ("LendingPaused", PaymentError::LendingPaused as u32),
        ("SubscriptionNotFound", PaymentError::SubscriptionNotFound as u32),
        ("SubscriptionAlreadyCancelled", PaymentError::SubscriptionAlreadyCancelled as u32),
        ("SubscriptionRenewalFailed", PaymentError::SubscriptionRenewalFailed as u32),
        ("BillingCycleInvalid", PaymentError::BillingCycleInvalid as u32),
        ("SubscriptionPaused", PaymentError::SubscriptionPaused as u32),
        ("TrialPeriodExpired", PaymentError::TrialPeriodExpired as u32),
        ("PaymentMethodInvalid", PaymentError::PaymentMethodInvalid as u32),
        ("SubscriptionTierNotAllowed", PaymentError::SubscriptionTierNotAllowed as u32),
        ("UsageQuotaExceeded", PaymentError::UsageQuotaExceeded as u32),
        ("SubscriptionUpgradePending", PaymentError::SubscriptionUpgradePending as u32),
        ("ZkProofInvalid", PaymentError::ZkProofInvalid as u32),
        ("PrivacyPoolNotConfigured", PaymentError::PrivacyPoolNotConfigured as u32),
        ("CommitmentAlreadySpent", PaymentError::CommitmentAlreadySpent as u32),
        ("NullifierAlreadyUsed", PaymentError::NullifierAlreadyUsed as u32),
        ("MerklePathInvalid", PaymentError::MerklePathInvalid as u32),
        ("PrivacyDepositTooLow", PaymentError::PrivacyDepositTooLow as u32),
        ("PrivacyWithdrawalPending", PaymentError::PrivacyWithdrawalPending as u32),
        ("StealthAddressInvalid", PaymentError::StealthAddressInvalid as u32),
        ("ConfidentialTransferFailed", PaymentError::ConfidentialTransferFailed as u32),
        ("PrivacyPaused", PaymentError::PrivacyPaused as u32),
        ("NotificationServiceDown", PaymentError::NotificationServiceDown as u32),
        ("MessageTooLong", PaymentError::MessageTooLong as u32),
        ("RecipientUnsubscribed", PaymentError::RecipientUnsubscribed as u32),
        ("NotificationDeliveryFailed", PaymentError::NotificationDeliveryFailed as u32),
        ("NotificationRateLimited", PaymentError::NotificationRateLimited as u32),
        ("MessageSignatureInvalid", PaymentError::MessageSignatureInvalid as u32),
        ("InboxFull", PaymentError::InboxFull as u32),
        ("NotificationTemplateInvalid", PaymentError::NotificationTemplateInvalid as u32),
        ("MessageExpired", PaymentError::MessageExpired as u32),
        ("NotificationChannelClosed", PaymentError::NotificationChannelClosed as u32),
        ("ReportGenerationFailed", PaymentError::ReportGenerationFailed as u32),
        ("AnalyticsDataMissing", PaymentError::AnalyticsDataMissing as u32),
        ("MetricOutOfRange", PaymentError::MetricOutOfRange as u32),
        ("ReportTooLarge", PaymentError::ReportTooLarge as u32),
        ("SnapshotNotFound", PaymentError::SnapshotNotFound as u32),
        ("AggregationWindowInvalid", PaymentError::AggregationWindowInvalid as u32),
        ("DataRetentionExpired", PaymentError::DataRetentionExpired as u32),
        ("ReportAccessDenied", PaymentError::ReportAccessDenied as u32),
        ("AnalyticsQuotaExceeded", PaymentError::AnalyticsQuotaExceeded as u32),
        ("ExportFormatUnsupported", PaymentError::ExportFormatUnsupported as u32),
        ("SepProtocolViolation", PaymentError::SepProtocolViolation as u32),
        ("AssetNotSepCompliant", PaymentError::AssetNotSepCompliant as u32),
        ("CrossContractVersionMismatch", PaymentError::CrossContractVersionMismatch as u32),
        ("InterfaceNotImplemented", PaymentError::InterfaceNotImplemented as u32),
        ("StandardsComplianceFailed", PaymentError::StandardsComplianceFailed as u32),
        ("ProtocolUpgradeRequired", PaymentError::ProtocolUpgradeRequired as u32),
        ("InteropHandshakeFailed", PaymentError::InteropHandshakeFailed as u32),
        ("NamespaceCollision", PaymentError::NamespaceCollision as u32),
        ("ExternalSystemUnavailable", PaymentError::ExternalSystemUnavailable as u32),
        ("InteropRateLimitExceeded", PaymentError::InteropRateLimitExceeded as u32),
        ("ContractUpgradeScheduled", PaymentError::ContractUpgradeScheduled as u32),
        ("MaintenanceModeActive", PaymentError::MaintenanceModeActive as u32),
        ("CircuitBreakerTripped", PaymentError::CircuitBreakerTripped as u32),
        ("EmergencyFreezeActive", PaymentError::EmergencyFreezeActive as u32),
        ("SystemClockDriftDetected", PaymentError::SystemClockDriftDetected as u32),
        ("LedgerVersionUnsupported", PaymentError::LedgerVersionUnsupported as u32),
        ("NetworkPartitionDetected", PaymentError::NetworkPartitionDetected as u32),
        ("ResourceExhaustionWarning", PaymentError::ResourceExhaustionWarning as u32),
        ("GracePeriodActive", PaymentError::GracePeriodActive as u32),
        ("ConfigurationInvalid", PaymentError::ConfigurationInvalid as u32),
        ("SystemFatalError", PaymentError::SystemFatalError as u32),
        ("RevocationNotFound", PaymentError::RevocationNotFound as u32),
        ("RevocationNotDue", PaymentError::RevocationNotDue as u32),
        ("RevocationAlreadyExecuted", PaymentError::RevocationAlreadyExecuted as u32),
        ("CannotRevokeSelf", PaymentError::CannotRevokeSelf as u32),
        ("NoPendingOwner", PaymentError::NoPendingOwner as u32),
        ("MathOverflow", PaymentError::MathOverflow as u32),
        ("StreamInvariantViolated", PaymentError::StreamInvariantViolated as u32),
    ]
}

#[test]
fn every_payment_error_discriminant_is_unique() {
    let variants = all_variants();
    let mut seen: HashMap<u32, &str> = HashMap::new();
    let mut duplicates: Vec<String> = Vec::new();

    for (name, code) in &variants {
        if let Some(existing) = seen.get(code) {
            duplicates.push(format!(
                "code {} is shared by '{}' and '{}'",
                code, existing, name
            ));
        } else {
            seen.insert(*code, name);
        }
    }

    assert!(
        duplicates.is_empty(),
        "Duplicate PaymentError discriminants found:\n{}",
        duplicates.join("\n")
    );
}

#[test]
fn discriminants_are_contiguous_from_1_to_max() {
    let variants = all_variants();
    let max_code = variants.iter().map(|(_, c)| *c).max().unwrap_or(0);
    let min_code = variants.iter().map(|(_, c)| *c).min().unwrap_or(0);

    assert_eq!(min_code, 1, "Minimum discriminant should be 1");
    assert_eq!(
        max_code as usize,
        variants.len(),
        "Expected {} variants for codes 1..={}, got {}",
        max_code,
        max_code,
        variants.len()
    );
}

#[test]
fn variant_count_matches_catalog() {
    let variants = all_variants();
    // The TypeScript catalog should have exactly as many entries as Rust variants.
    // This is verified by the TS-side test; here we just record the count.
    assert_eq!(
        variants.len(),
        307,
        "Expected 307 PaymentError variants (codes 1..=307)"
    );
}
