// SPDX-License-Identifier: MIT
import { describe, it, expect } from "vitest";
import { buildSignedPayload } from "@/lib/webhook-deliver";
import { verifyWebhookSignature } from "@/lib/webhook-verify";

describe("Webhook Signature Verification & Reference Client", () => {
  const secret = "whsec_test_secret_key_12345";
  const basePayload = {
    event: "payment.succeeded",
    timestamp: new Date().toISOString(),
    data: {
      paymentId: "pay_98765",
      amount: 150.75,
      asset: "USDC",
      payer: "GA11111111111111111111111111111111111111111111111111111111",
      payee: "GB22222222222222222222222222222222222222222222222222222222",
    },
  };

  it("successfully verifies a valid signed payload generated by buildSignedPayload", () => {
    const { body, signature } = buildSignedPayload(basePayload, secret);
    const result = verifyWebhookSignature(body, signature, secret);

    expect(result.valid).toBe(true);
    expect(result.payload?.event).toBe("payment.succeeded");
    expect(result.payload?.data.paymentId).toBe("pay_98765");
  });

  it("rejects payload when body has been tampered with in transit", () => {
    const { body, signature } = buildSignedPayload(basePayload, secret);
    const tampered = JSON.parse(body);
    tampered.data.amount = 999999.99; // Attacker altered amount

    const result = verifyWebhookSignature(JSON.stringify(tampered), signature, secret);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("Signature mismatch");
  });

  it("rejects payload when an incorrect webhook secret is used", () => {
    const { body, signature } = buildSignedPayload(basePayload, secret);
    const result = verifyWebhookSignature(body, signature, "whsec_wrong_secret_key");

    expect(result.valid).toBe(false);
    expect(result.reason).toBe("Signature mismatch");
  });

  it("rejects replayed requests with timestamps outside the tolerance window", () => {
    const oldTimestamp = new Date(Date.now() - 600 * 1000).toISOString(); // 10 minutes old
    const expiredPayload = { ...basePayload, timestamp: oldTimestamp };
    const { body, signature } = buildSignedPayload(expiredPayload, secret);

    const result = verifyWebhookSignature(body, signature, secret, { toleranceSeconds: 300 });
    expect(result.valid).toBe(false);
    expect(result.reason).toMatch(/Timestamp outside tolerance window/);
  });

  it("accepts requests within custom tolerance window", () => {
    const fixedNow = 1787750000000;
    const recentPayload = {
      ...basePayload,
      timestamp: new Date(fixedNow - 60000).toISOString(), // 1 minute ago
    };
    const { body, signature } = buildSignedPayload(recentPayload, secret);

    const result = verifyWebhookSignature(body, signature, secret, {
      toleranceSeconds: 300,
      now: fixedNow,
    });
    expect(result.valid).toBe(true);
  });

  it("handles missing signatures, missing secrets, or malformed JSON gracefully", () => {
    expect(verifyWebhookSignature("{}", "", secret).valid).toBe(false);
    expect(verifyWebhookSignature("{}", "sig", "").valid).toBe(false);
    expect(verifyWebhookSignature("not-json", "sig", secret).valid).toBe(false);
  });
});

